### ISSUE TITLE
Output the coverage report (as is)

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/ptt-cli#6]
## Description

As a user, i want to receive the coverage report (the one currently being generated by the dapp certification tool). If no coverage report is generated, output a blank report.

## Acceptance Criteria

- [ ] The current coverage report is output by the tool

## Dependencies
Discussion need to happen between @Ali-Hill and @bogdan-manole. If cannot happen soon in the sprint, move this ticket to sprint 6 PI7

**Comment by robpangilinanioi** [comment]
Need to have a discussion about what the acceptance criteria for this item should be.
